config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :kombuchas

  resources :brands, only: [:index, :new, :create, :show] do
    resources :kombuchas, only: [:index, :new, :show, :create]
  end

  # INDEX:
  # get '/kombuchas', to: 'kombuchas#index', as: "kombuchas"
  #
  # SHOW:
  # get '/kombuchas/:id', to: 'kombuchas#show', :as => :kombucha
  #
  # EDIT:
  # get '/kombuchas/:id/edit', to: 'kombuchas#edit', :as => :edit_kombucha

  # '/kombuchas/5/brand' this COULD work, but the pattern is more to start with model that has many of somethingg else:
  # '/brands/2/kombuchas'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :kombuchas, dependent: :destroy

  accepts_nested_attributes_for :kombuchas
end

app/models/concerns/TwoWordsValidator.rb
class TwoWordsValidator < ActiveModel::EachValidator

  def validate_each(instance, attribute, value)
    if value.split(" ").count != 2
      instance.errors.add(attribute, "Must be two words")
    end
  end

end

app/models/kombucha.rb
class Kombucha < ApplicationRecord
  #Use this format if you want to apply several validations to several attributes
  #validates :flavor, :brew_time, :notes, presence: true, numericality: true
  #Use this format if you only want to apply one validation to several attributes
  # validates_presence_of :brew_time
  # validates_uniqueness_of :flavor
  # validates :flavor, length: {maximum: 15, minimum: 5}, presence: true

  # validate :maximum_total_word_count
  #
  # def maximum_total_word_count
  #   if flavor.length + notes.length > 500
  #     errors.add(total_length: "You have too many words overall")
  #   end
  # end

  belongs_to :brand
  accepts_nested_attributes_for :brand, reject_if: proc { |attributes| attributes['name'].blank? }

  #accepts_nested_attributes_for writes this method for us:
  # def brand_attributes=(hash)
  #   byebug
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in, :current_user, :verify_that_user_is_owner_of_record #makes these methods available to all views

  def loggin
    @user = User.find_by(username: params[:username])
  end

  private #private methods in the application controller are helpers for all controllers

  def redirect_if_not_logged_in
    #redirect the user if the user is not logged in
  end

  def logged_in?
    #check to see if user is logged in
  end

  def current_user
    #check to see who the current user is
  end

  def verify_that_user_is_owner_of_record
    "Checking to see if this works in all views" #HINT: It does
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all
  end

  #Maybe we could write a show route that displays all of the kombuchas for that brand
  # def show
  #   @brand = Brand.find(params[:id])
  # end
  #But maybe also because the show page would just display a list of kombuchas that belong to this brand, we could consider it an index page for the kombuchas that belong to this brand

  def new
    @brand = Brand.new
    params[:kombuchas].to_i.times do
      @brand.kombuchas.build #@brand.kombuchas.build - we're making an instance of something that would belong to the brand
    end
    render :new
  end

  def create
    @brand = Brand.create(brand_params)
    byebug
  end

  private

  def brand_params
    params.require(:brand).permit(:name, kombuchas_attributes: [:flavor, :brew_time, :notes])
  end

end

app/controllers/kombuchas_controller.rb
class KombuchasController < ApplicationController
  before_action :get_kombucha, only: [:show, :edit, :update, :destroy] #this method came from this controller
  before_action :redirect_if_not_logged_in, only: [:new, :createm, :edit, :update] #this method came from the ApplicationController
  helper_method :verify_that_user_is_owner_of_kombucha #makes this method available to the view

  def index
    if params[:brand_id]
      @brand = Brand.find_by(id: params[:brand_id])
      if @brand
        @kombuchas = @brand.kombuchas
      end
    else
      @kombuchas = Kombucha.all
    end
    # render :index
  end

  def show # '/kombuchas/:id'
    # render :show
  end

  def new
    @kombucha = Kombucha.new
    #helpers.kombucha_notes(kombucha)
    #This helper method is available to us from the KombuchasHelper module, if we want to use it.
    #I don't see a need for it though, this is just an example
    if params[:brand_id]
      brand = Brand.find_by(id: params[:brand_id])
      if brand
        @kombucha.brand = brand
      end
    else
      @brands = Brand.all
      @kombucha.build_brand #we're making an instance of something that the kombucha will belong to
    end
    # render :new
  end

  def create
    @kombucha = Kombucha.new(kombucha_params(params_array))
    if @kombucha.save
      if params[:brand_id]
        redirect_to brand_kombucha_path(params[:brand_id], @kombucha.id)
      else
      redirect_to kombucha_path(@kombucha)
    end
    else
      @brands = Brand.all
      render :new
    end
    # redirect_to "/kombuchas/#{kombucha.id}"
  end

  def edit
    @brands = Brand.all
    # render :edit
  end

  def update
    @kombucha.assign_attributes(kombucha_params(params_array))
    if @kombucha.save
      redirect_to kombucha_path(@kombucha)
    else
      @brands = Brand.all
      render :edit
    end
  end

  def destroy
    @kombucha.destroy
    redirect_to
  end

  private #these are methods that are only useful FOR THIS controller

  def verify_that_user_is_owner_of_kombucha
    "Testing to see if this kombucha helper method works in a view for another controller" #HINT: It doesn't
  end

  def get_kombucha #this method is never going to be called in another controller OR in another view
    @kombucha = Kombucha.find_by(id: params[:id])
  end

  def kombucha_params(array_args)
    params.require(:kombucha).permit(array_args)
  end

  def params_array
    [:flavor, :notes, :brew_time, :brand_id, brand_attributes: [:name]]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/kombuchas_helper.rb
module KombuchasHelper
  #These helpers are available in ALL views and ALL controllers.
  #However, they get their own file because it's easier to keep them organize.

  #The methods that go here are generally for view formatting to take logic out of views
  #BUT they are available to use in the controllers as well.

  def kombucha_notes(kombucha)
    "<h3>Notes:</h3>
    <p>#{kombucha.notes.blank? ? "This kombocha doesn't have a note" : kombucha.notes}</p>
    ".html_safe #Yes you can write HTML as a string if you use .html_safe
  end


end

app/views/brands/index.erb
<h2>All Kombucha Brands</h2>

<ul>
<% @brands.each do |brand| %>
  <li>
    <%= link_to brand.name, brand_kombuchas_path(brand) %>
  </li>
<% end %>
</ul>

app/views/brands/new.erb
<h2>Make A New Brand</h2>

<%= verify_that_user_is_owner_of_record %>

<%= form_with model: @brand do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <p>Make First Kombucha!</p>
  <br>
  <%= f.fields_for :kombuchas do |kf| %>
    <%= kf.label :flavor %>
    <%= kf.text_field  :flavor%>
    <br>
    <%= kf.label :brew_time %>
    <%= kf.number_field :brew_time %>
    <br>
    <%= kf.label :notes %>
    <%= kf.text_area :notes %>
    <br>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/brands/show.erb
<h2><%= @brand.name %></h2>

<p>This could be a potential show page for a brand; it shows all of the kombuchas that belong to it. HOWEVER this could also be considered an index route for kombuchas, but kombuchas from a specific brand</p>
<ul>
<% @brand.kombuchas.each do |kombucha| %>
  <li><%= kombucha.flavor %></li>
<% end %>
</ul>

app/views/kombuchas/_form.erb
<%= render partial: 'layouts/errors', locals: {instance: @kombucha} %>

<%= form_with model: @kombucha.brand.id ? [@kombucha.brand, @kombucha] : @kombucha, local: true do |f| %>
  <%= f.label :flavor %>
  <%= f.text_field  :flavor%>
  <br>
  <%= f.label :brew_time %>
  <%= f.number_field :brew_time %>
  <br>
  <%= f.label :notes %>
  <%= f.text_area :notes %>
  <br>
  <% if @kombucha.brand.id %>
    <%= f.hidden_field :brand_id %>
  <% else %>
    <%= f.label :brand %>
    <%= f.collection_select :brand_id, @brands, :id, :name %>
    <br>
    <p>Don't see the brand? Make a new one!</p>
    <%= f.fields_for :brand do |bf| %>
      <%= bf.label :name %>
      <%= bf.text_field :name %>
    <% end %>
    <br>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/kombuchas/edit.erb
<h2>Edit A Kombucha!</h2>

<%= render 'form' %>

<br>

<%= form_with model: @kombucha, method: :delete do |f| %>
  <%= f.submit "Delete This Kombucha" %>
<% end %>

app/views/kombuchas/index.erb
<h2><%= @brand ? "All Kombuchas for " + @brand.name : "Kombuchas Index!" %></h2>

<ul>
  <% @kombuchas.each do |k| %>
    <li><%= link_to "#{k.flavor}!", brand_kombucha_path(k.brand.id, k) %></li>
  <% end %>
</ul>

<br>
<br>

app/views/kombuchas/new.erb
<h2>Make a new Kombucha!</h2>

<%= render 'form' %>

app/views/kombuchas/show.erb
<h2><%= @kombucha.flavor %></h2>

<h3>Brew Time: <%= @kombucha.brew_time %></h3>

<h3>Brand: <%= @kombucha.brand.name %></h3>

<%= kombucha_notes(@kombucha) %>
<br>
<br>
<%= link_to "Go Back To Kombuchas Index", "/kombuchas" %>


<%# <%= verify_that_user_is_owner_of_kombucha(@kombucha, current_user) ? link_to "Edit!", edit_kombucha_path(@kombucha) : null %>

app/views/layouts/_errors.erb
<% if !instance.errors.full_messages.empty? %>
  <div>
    Errors:
    <ul>
      <% instance.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
  <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KombuchasApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>